name: Create GitHub App Installation Token from OIDC
description: Generate Temporary Token

author: Atolycs

branding:
  icon: log-in
  color: green

inputs:
  app-id:
    description: Auth GitHub App ID
    required: false
    default: 1688372
  provider-endpoint:
    description: URL for Credential provider
    required: false
  repositories:
    description: repositories you want to access. It is a list of global node ids of the repositories
    required: false
#outputs:


runs:
  using: node20
  main: dist/main.js
  post-if: always()
