name: Test create-gha-token action

on:
  workflow_dispatch:


jobs:
  auth:
    name: GitHub App Auth Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Run
        uses: atolycs/gh-action-util/create-gha-oidc-token@feature/create-gha-oidc-token
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}

      - name: Authentication Test
        env: 
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh auth status
          gh api /octocat

